services:
  php:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
